apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: python-app-pipeline
description: "Pipeline to deploy Python app to GKE"
serialPipeline:
  stages:
    - targetId: staging
      profiles: [staging]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: "Staging GKE cluster"
gke:
  cluster: projects/PROJECT_ID/locations/us-central1-c/clusters/staging-cluster
