apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-sample-app
  template:
    metadata:
      labels:
        app: python-sample-app
    spec:
      containers:
        - name: python-sample-app
          image: python-sample-app # substituted by Cloud Deploy
          ports:
            - containerPort: 8080
